apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-cluster
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  componentSpecs:
    - disableExporter: false
      replicas: 2
  postgresVersion: 17
  users:
    - name: pg-cluster
      databases:
        - testmk
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi
