apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-cluster-multi-repo
spec:
  postgresVersion: 17
  instances:
    - dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  backups:
    pgbackrest:
      configuration:
      - secret:
          name: pgo-multi-repo-creds
      global:
        repo2-path: /pgbackrest/postgres-operator/hippo-multi-repo/repo2
        repo3-path: /pgbackrest/postgres-operator/hippo-multi-repo/repo3
        repo4-path: /pgbackrest/postgres-operator/hippo-multi-repo/repo4
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi
      - name: repo2
        s3:
          bucket: "pg-cluster-bucket"
          endpoint: ""
          region: ""
      - name: repo3
        gcs:
          bucket: "pg-cluster-bucket"
      - name: repo4
        azure:
          container: ""
